# Generated by Django 5.0.2 on 2024-06-03 20:53

import authuser.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', authuser.models.CustomUserManager()),
            ],
        ),
    ]
